// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type ContactusDocumentDataSlicesSlice = ContactUsSupportSlice | ContacUsSlice;

/**
 * Content for ContactUs documents
 */
interface ContactusDocumentData {
  /**
   * Slice Zone field in *ContactUs*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: contactus.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ContactusDocumentDataSlicesSlice> /**
   * Meta Title field in *ContactUs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: contactus.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *ContactUs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: contactus.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *ContactUs*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contactus.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * ContactUs document from Prismic
 *
 * - **API ID**: `contactus`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactusDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ContactusDocumentData>,
    "contactus",
    Lang
  >;

type HomepageDocumentDataSlicesSlice =
  | FooterSlice
  | GrowYoursSlice
  | LogosSlice
  | MeetOurTeamSlice
  | AboutUsSlice
  | HeaderSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

type PricingDocumentDataSlicesSlice =
  | FreeComponentSlice
  | PricingfaqSlice
  | PricingCardsSlice
  | PricingAfterHeaderSlice;

/**
 * Content for Pricing documents
 */
interface PricingDocumentData {
  /**
   * Slice Zone field in *Pricing*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PricingDocumentDataSlicesSlice> /**
   * Meta Title field in *Pricing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: pricing.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Pricing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: pricing.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Pricing*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Pricing document from Prismic
 *
 * - **API ID**: `pricing`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PricingDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<PricingDocumentData>,
    "pricing",
    Lang
  >;

type TeamDocumentDataSlicesSlice = ClothesCardsSlice | PricingAfterHeaderSlice;

/**
 * Content for Team documents
 */
interface TeamDocumentData {
  /**
   * Slice Zone field in *Team*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: team.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<TeamDocumentDataSlicesSlice> /**
   * Meta Title field in *Team*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: team.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Team*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: team.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Team*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: team.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Team document from Prismic
 *
 * - **API ID**: `team`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TeamDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<TeamDocumentData>, "team", Lang>;

export type AllDocumentTypes =
  | ContactusDocument
  | HomepageDocument
  | PricingDocument
  | TeamDocument;

/**
 * Primary content in *AboutUs → Default → Primary*
 */
export interface AboutUsSliceDefaultPrimary {
  /**
   * Background field in *AboutUs → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.default.primary.background
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background: prismic.ImageField<never>;

  /**
   * Subtitle field in *AboutUs → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Title field in *AboutUs → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Text field in *AboutUs → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;

  /**
   * Button field in *AboutUs → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.default.primary.button
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button: prismic.KeyTextField;
}

/**
 * Default variation for AboutUs Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutUsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutUsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AboutUs*
 */
type AboutUsSliceVariation = AboutUsSliceDefault;

/**
 * AboutUs Shared Slice
 *
 * - **API ID**: `about_us`
 * - **Description**: AboutUs
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutUsSlice = prismic.SharedSlice<
  "about_us",
  AboutUsSliceVariation
>;

/**
 * Item in *ClothesCards → Default → Primary → SmallImages*
 */
export interface ClothesCardsSliceDefaultPrimarySmallImagesItem {
  /**
   * Image field in *ClothesCards → Default → Primary → SmallImages*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: clothes_cards.default.primary.smallImages[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * ImageMobile field in *ClothesCards → Default → Primary → SmallImages*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: clothes_cards.default.primary.smallImages[].imageMobile
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imageMobile: prismic.ImageField<never>;
}

/**
 * Primary content in *ClothesCards → Default → Primary*
 */
export interface ClothesCardsSliceDefaultPrimary {
  /**
   * BigImage field in *ClothesCards → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: clothes_cards.default.primary.bigImage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  bigImage: prismic.ImageField<never>;

  /**
   * MobileImage field in *ClothesCards → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: clothes_cards.default.primary.mobileImage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  mobileImage: prismic.ImageField<never>;

  /**
   * SmallImages field in *ClothesCards → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: clothes_cards.default.primary.smallImages[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  smallImages: prismic.GroupField<
    Simplify<ClothesCardsSliceDefaultPrimarySmallImagesItem>
  >;
}

/**
 * Default variation for ClothesCards Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ClothesCardsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ClothesCardsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ClothesCards*
 */
type ClothesCardsSliceVariation = ClothesCardsSliceDefault;

/**
 * ClothesCards Shared Slice
 *
 * - **API ID**: `clothes_cards`
 * - **Description**: ClothesCards
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ClothesCardsSlice = prismic.SharedSlice<
  "clothes_cards",
  ClothesCardsSliceVariation
>;

/**
 * Item in *ContacUs → Default → Primary → SocialLinks*
 */
export interface ContacUsSliceDefaultPrimarySocialLinksItem {
  /**
   * Link field in *ContacUs → Default → Primary → SocialLinks*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contac_us.default.primary.socialLinks[].link
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link: prismic.KeyTextField;

  /**
   * Logo field in *ContacUs → Default → Primary → SocialLinks*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contac_us.default.primary.socialLinks[].logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;
}

/**
 * Primary content in *ContacUs → Default → Primary*
 */
export interface ContacUsSliceDefaultPrimary {
  /**
   * Image field in *ContacUs → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contac_us.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Subtitle field in *ContacUs → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contac_us.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Title field in *ContacUs → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contac_us.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Descr field in *ContacUs → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contac_us.default.primary.descr
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  descr: prismic.KeyTextField;

  /**
   * Phone field in *ContacUs → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contac_us.default.primary.phone
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phone: prismic.KeyTextField;

  /**
   * Email field in *ContacUs → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contac_us.default.primary.email
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;

  /**
   * SocialLinks field in *ContacUs → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: contac_us.default.primary.socialLinks[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  socialLinks: prismic.GroupField<
    Simplify<ContacUsSliceDefaultPrimarySocialLinksItem>
  >;
}

/**
 * Default variation for ContacUs Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContacUsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContacUsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContacUs*
 */
type ContacUsSliceVariation = ContacUsSliceDefault;

/**
 * ContacUs Shared Slice
 *
 * - **API ID**: `contac_us`
 * - **Description**: ContacUs
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContacUsSlice = prismic.SharedSlice<
  "contac_us",
  ContacUsSliceVariation
>;

/**
 * Item in *ContactUsSupport → Default → Primary → SupportCards*
 */
export interface ContactUsSupportSliceDefaultPrimarySupportCardsItem {
  /**
   * Logo field in *ContactUsSupport → Default → Primary → SupportCards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_us_support.default.primary.supportCards[].logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * EmailFirst field in *ContactUsSupport → Default → Primary → SupportCards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_us_support.default.primary.supportCards[].emailFirst
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  emailFirst: prismic.KeyTextField;

  /**
   * EmailSecond field in *ContactUsSupport → Default → Primary → SupportCards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_us_support.default.primary.supportCards[].emailSecond
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  emailSecond: prismic.KeyTextField;

  /**
   * Button field in *ContactUsSupport → Default → Primary → SupportCards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_us_support.default.primary.supportCards[].button
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button: prismic.KeyTextField;
}

/**
 * Primary content in *ContactUsSupport → Default → Primary*
 */
export interface ContactUsSupportSliceDefaultPrimary {
  /**
   * Subtitle field in *ContactUsSupport → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_us_support.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Title field in *ContactUsSupport → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_us_support.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * SupportCards field in *ContactUsSupport → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_us_support.default.primary.supportCards[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  supportCards: prismic.GroupField<
    Simplify<ContactUsSupportSliceDefaultPrimarySupportCardsItem>
  >;
}

/**
 * Default variation for ContactUsSupport Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactUsSupportSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactUsSupportSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContactUsSupport*
 */
type ContactUsSupportSliceVariation = ContactUsSupportSliceDefault;

/**
 * ContactUsSupport Shared Slice
 *
 * - **API ID**: `contact_us_support`
 * - **Description**: ContactUsSupport
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactUsSupportSlice = prismic.SharedSlice<
  "contact_us_support",
  ContactUsSupportSliceVariation
>;

/**
 * Item in *Footer → Default → Primary → Lists*
 */
export interface FooterSliceDefaultPrimaryListsItem {
  /**
   * List field in *Footer → Default → Primary → Lists*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.lists[].list
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  list: prismic.KeyTextField;
}

/**
 * Item in *Footer → Default → Primary → Company Info*
 */
export interface FooterSliceDefaultPrimaryCompanyInfoItem {
  /**
   * Item field in *Footer → Default → Primary → Company Info*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.companyInfo[].item
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  item: prismic.KeyTextField;
}

/**
 * Item in *Footer → Default → Primary → Legal*
 */
export interface FooterSliceDefaultPrimaryLegalItem {
  /**
   * Item field in *Footer → Default → Primary → Legal*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.legal[].item
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  item: prismic.KeyTextField;
}

/**
 * Item in *Footer → Default → Primary → Features*
 */
export interface FooterSliceDefaultPrimaryFeaturesItem {
  /**
   * Item field in *Footer → Default → Primary → Features*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.features[].item
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  item: prismic.KeyTextField;
}

/**
 * Item in *Footer → Default → Primary → Resources*
 */
export interface FooterSliceDefaultPrimaryResourcesItem {
  /**
   * Item field in *Footer → Default → Primary → Resources*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.resources[].item
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  item: prismic.KeyTextField;
}

/**
 * Primary content in *Footer → Default → Primary*
 */
export interface FooterSliceDefaultPrimary {
  /**
   * Logo field in *Footer → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.logo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  logo: prismic.KeyTextField;

  /**
   * Facebook field in *Footer → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.facebook
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  facebook: prismic.ImageField<never>;

  /**
   * Instagram field in *Footer → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.instagram
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  instagram: prismic.ImageField<never>;

  /**
   * Twitter field in *Footer → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.twitter
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  twitter: prismic.ImageField<never>;

  /**
   * Lists field in *Footer → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.lists[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  lists: prismic.GroupField<Simplify<FooterSliceDefaultPrimaryListsItem>>;

  /**
   * Company Info field in *Footer → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.companyInfo[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  companyInfo: prismic.GroupField<
    Simplify<FooterSliceDefaultPrimaryCompanyInfoItem>
  >;

  /**
   * Legal field in *Footer → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.legal[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  legal: prismic.GroupField<Simplify<FooterSliceDefaultPrimaryLegalItem>>;

  /**
   * Features field in *Footer → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.features[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  features: prismic.GroupField<Simplify<FooterSliceDefaultPrimaryFeaturesItem>>;

  /**
   * Resources field in *Footer → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.resources[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  resources: prismic.GroupField<
    Simplify<FooterSliceDefaultPrimaryResourcesItem>
  >;
}

/**
 * Default variation for Footer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FooterSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Footer*
 */
type FooterSliceVariation = FooterSliceDefault;

/**
 * Footer Shared Slice
 *
 * - **API ID**: `footer`
 * - **Description**: Footer
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterSlice = prismic.SharedSlice<"footer", FooterSliceVariation>;

/**
 * Item in *FreeComponent → Default → Primary → SocialLogos*
 */
export interface FreeComponentSliceDefaultPrimarySocialLogosItem {
  /**
   * SocialLogo field in *FreeComponent → Default → Primary → SocialLogos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: free_component.default.primary.socialLogos[].socialLogo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  socialLogo: prismic.ImageField<never>;

  /**
   * Link field in *FreeComponent → Default → Primary → SocialLogos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: free_component.default.primary.socialLogos[].link
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link: prismic.KeyTextField;
}

/**
 * Primary content in *FreeComponent → Default → Primary*
 */
export interface FreeComponentSliceDefaultPrimary {
  /**
   * Title field in *FreeComponent → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: free_component.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *FreeComponent → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: free_component.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Button field in *FreeComponent → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: free_component.default.primary.button
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button: prismic.KeyTextField;

  /**
   * SocialLogos field in *FreeComponent → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: free_component.default.primary.socialLogos[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  socialLogos: prismic.GroupField<
    Simplify<FreeComponentSliceDefaultPrimarySocialLogosItem>
  >;
}

/**
 * Default variation for FreeComponent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FreeComponentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FreeComponentSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FreeComponent*
 */
type FreeComponentSliceVariation = FreeComponentSliceDefault;

/**
 * FreeComponent Shared Slice
 *
 * - **API ID**: `free_component`
 * - **Description**: FreeComponent
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FreeComponentSlice = prismic.SharedSlice<
  "free_component",
  FreeComponentSliceVariation
>;

/**
 * Primary content in *GrowYours → Default → Primary*
 */
export interface GrowYoursSliceDefaultPrimary {
  /**
   * Subtitle field in *GrowYours → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: grow_yours.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Title field in *GrowYours → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: grow_yours.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Text field in *GrowYours → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: grow_yours.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;

  /**
   * Button field in *GrowYours → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: grow_yours.default.primary.button
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button: prismic.KeyTextField;

  /**
   * Image field in *GrowYours → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: grow_yours.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for GrowYours Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GrowYoursSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<GrowYoursSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *GrowYours*
 */
type GrowYoursSliceVariation = GrowYoursSliceDefault;

/**
 * GrowYours Shared Slice
 *
 * - **API ID**: `grow_yours`
 * - **Description**: GrowYours
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GrowYoursSlice = prismic.SharedSlice<
  "grow_yours",
  GrowYoursSliceVariation
>;

/**
 * Item in *Header → Default → Primary → List*
 */
export interface HeaderSliceDefaultPrimaryListItem {
  /**
   * ListItem field in *Header → Default → Primary → List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.list[].listItem
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  listItem: prismic.KeyTextField;

  /**
   * Link field in *Header → Default → Primary → List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.list[].link
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link: prismic.KeyTextField;
}

/**
 * Primary content in *Header → Default → Primary*
 */
export interface HeaderSliceDefaultPrimary {
  /**
   * MainLogo field in *Header → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.mainLogo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  mainLogo: prismic.KeyTextField;

  /**
   * List field in *Header → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.list[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  list: prismic.GroupField<Simplify<HeaderSliceDefaultPrimaryListItem>>;

  /**
   * ButtonLogin field in *Header → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.buttonLogin
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttonLogin: prismic.KeyTextField;

  /**
   * ButtonMember field in *Header → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.buttonMember
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttonMember: prismic.KeyTextField;

  /**
   * ButtonArrow field in *Header → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.buttonArrow
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  buttonArrow: prismic.ImageField<never>;
}

/**
 * Default variation for Header Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeaderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Header*
 */
type HeaderSliceVariation = HeaderSliceDefault;

/**
 * Header Shared Slice
 *
 * - **API ID**: `header`
 * - **Description**: Header
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderSlice = prismic.SharedSlice<"header", HeaderSliceVariation>;

/**
 * Item in *Logos → Default → Primary → Logos*
 */
export interface LogosSliceDefaultPrimaryLogosItem {
  /**
   * Logo field in *Logos → Default → Primary → Logos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: logos.default.primary.logos[].logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;
}

/**
 * Primary content in *Logos → Default → Primary*
 */
export interface LogosSliceDefaultPrimary {
  /**
   * Title field in *Logos → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: logos.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Text field in *Logos → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: logos.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;

  /**
   * Logos field in *Logos → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: logos.default.primary.logos[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  logos: prismic.GroupField<Simplify<LogosSliceDefaultPrimaryLogosItem>>;
}

/**
 * Default variation for Logos Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LogosSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LogosSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Logos*
 */
type LogosSliceVariation = LogosSliceDefault;

/**
 * Logos Shared Slice
 *
 * - **API ID**: `logos`
 * - **Description**: Logos
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LogosSlice = prismic.SharedSlice<"logos", LogosSliceVariation>;

/**
 * Item in *MeetOurTeam → Default → Primary → Users*
 */
export interface MeetOurTeamSliceDefaultPrimaryUsersItem {
  /**
   * Image field in *MeetOurTeam → Default → Primary → Users*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: meet_our_team.default.primary.users[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Name field in *MeetOurTeam → Default → Primary → Users*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: meet_our_team.default.primary.users[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Profession field in *MeetOurTeam → Default → Primary → Users*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: meet_our_team.default.primary.users[].profession
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  profession: prismic.KeyTextField;

  /**
   * FacebookLlink field in *MeetOurTeam → Default → Primary → Users*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: meet_our_team.default.primary.users[].facebookLink
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  facebookLink: prismic.KeyTextField;

  /**
   * InstagramLink field in *MeetOurTeam → Default → Primary → Users*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: meet_our_team.default.primary.users[].instagramLink
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  instagramLink: prismic.KeyTextField;

  /**
   * TwitterLink field in *MeetOurTeam → Default → Primary → Users*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: meet_our_team.default.primary.users[].twitterLink
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  twitterLink: prismic.KeyTextField;

  /**
   * Uid field in *MeetOurTeam → Default → Primary → Users*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: meet_our_team.default.primary.users[].uid
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  uid: prismic.KeyTextField;
}

/**
 * Primary content in *MeetOurTeam → Default → Primary*
 */
export interface MeetOurTeamSliceDefaultPrimary {
  /**
   * Title field in *MeetOurTeam → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: meet_our_team.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Text field in *MeetOurTeam → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: meet_our_team.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;

  /**
   * Users field in *MeetOurTeam → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: meet_our_team.default.primary.users[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  users: prismic.GroupField<Simplify<MeetOurTeamSliceDefaultPrimaryUsersItem>>;

  /**
   * Facebook field in *MeetOurTeam → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: meet_our_team.default.primary.facebook
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  facebook: prismic.ImageField<never>;

  /**
   * Instagram field in *MeetOurTeam → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: meet_our_team.default.primary.instagram
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  instagram: prismic.ImageField<never>;

  /**
   * Twitter field in *MeetOurTeam → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: meet_our_team.default.primary.twitter
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  twitter: prismic.ImageField<never>;
}

/**
 * Default variation for MeetOurTeam Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MeetOurTeamSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MeetOurTeamSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *MeetOurTeam*
 */
type MeetOurTeamSliceVariation = MeetOurTeamSliceDefault;

/**
 * MeetOurTeam Shared Slice
 *
 * - **API ID**: `meet_our_team`
 * - **Description**: MeetOurTeam
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MeetOurTeamSlice = prismic.SharedSlice<
  "meet_our_team",
  MeetOurTeamSliceVariation
>;

/**
 * Primary content in *AfterHeader → Default → Primary*
 */
export interface PricingAfterHeaderSliceDefaultPrimary {
  /**
   * Subtitle field in *AfterHeader → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing_after_header.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Title field in *AfterHeader → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing_after_header.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * HomeLink field in *AfterHeader → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing_after_header.default.primary.homeLink
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  homeLink: prismic.KeyTextField;

  /**
   * PageLink field in *AfterHeader → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing_after_header.default.primary.pageLink
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  pageLink: prismic.KeyTextField;
}

/**
 * Default variation for AfterHeader Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PricingAfterHeaderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PricingAfterHeaderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AfterHeader*
 */
type PricingAfterHeaderSliceVariation = PricingAfterHeaderSliceDefault;

/**
 * AfterHeader Shared Slice
 *
 * - **API ID**: `pricing_after_header`
 * - **Description**: PricingAfterHeader
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PricingAfterHeaderSlice = prismic.SharedSlice<
  "pricing_after_header",
  PricingAfterHeaderSliceVariation
>;

/**
 * Item in *PricingCards → Default → Primary → Card*
 */
export interface PricingCardsSliceDefaultPrimaryCardItem {
  /**
   * Title field in *PricingCards → Default → Primary → Card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing_cards.default.primary.card[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *PricingCards → Default → Primary → Card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing_cards.default.primary.card[].subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Price field in *PricingCards → Default → Primary → Card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing_cards.default.primary.card[].price
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  price: prismic.KeyTextField;

  /**
   * YearlyPrice field in *PricingCards → Default → Primary → Card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing_cards.default.primary.card[].yearlyPrice
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  yearlyPrice: prismic.KeyTextField;

  /**
   * GreenCircle field in *PricingCards → Default → Primary → Card*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing_cards.default.primary.card[].greenCircle
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  greenCircle: prismic.ImageField<never>;

  /**
   * GreyCircle field in *PricingCards → Default → Primary → Card*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing_cards.default.primary.card[].greyCircle
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  greyCircle: prismic.ImageField<never>;

  /**
   * Button field in *PricingCards → Default → Primary → Card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing_cards.default.primary.card[].button
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button: prismic.KeyTextField;

  /**
   * uid field in *PricingCards → Default → Primary → Card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing_cards.default.primary.card[].uid
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  uid: prismic.KeyTextField;
}

/**
 * Primary content in *PricingCards → Default → Primary*
 */
export interface PricingCardsSliceDefaultPrimary {
  /**
   * Card field in *PricingCards → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing_cards.default.primary.card[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  card: prismic.GroupField<Simplify<PricingCardsSliceDefaultPrimaryCardItem>>;
}

/**
 * Default variation for PricingCards Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PricingCardsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PricingCardsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PricingCards*
 */
type PricingCardsSliceVariation = PricingCardsSliceDefault;

/**
 * PricingCards Shared Slice
 *
 * - **API ID**: `pricing_cards`
 * - **Description**: PricingCards
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PricingCardsSlice = prismic.SharedSlice<
  "pricing_cards",
  PricingCardsSliceVariation
>;

/**
 * Item in *Pricingfaq → Default → Primary → Items*
 */
export interface PricingfaqSliceDefaultPrimaryItemsItem {
  /**
   * Subtitle field in *Pricingfaq → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricingfaq.default.primary.items[].subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Descr field in *Pricingfaq → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricingfaq.default.primary.items[].descr
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  descr: prismic.KeyTextField;
}

/**
 * Primary content in *Pricingfaq → Default → Primary*
 */
export interface PricingfaqSliceDefaultPrimary {
  /**
   * Title field in *Pricingfaq → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricingfaq.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Text field in *Pricingfaq → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricingfaq.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;

  /**
   * Items field in *Pricingfaq → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: pricingfaq.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<Simplify<PricingfaqSliceDefaultPrimaryItemsItem>>;

  /**
   * Bottom field in *Pricingfaq → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricingfaq.default.primary.bottom
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  bottom: prismic.KeyTextField;
}

/**
 * Default variation for Pricingfaq Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PricingfaqSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PricingfaqSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Pricingfaq*
 */
type PricingfaqSliceVariation = PricingfaqSliceDefault;

/**
 * Pricingfaq Shared Slice
 *
 * - **API ID**: `pricingfaq`
 * - **Description**: Pricingfaq
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PricingfaqSlice = prismic.SharedSlice<
  "pricingfaq",
  PricingfaqSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ContactusDocument,
      ContactusDocumentData,
      ContactusDocumentDataSlicesSlice,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      PricingDocument,
      PricingDocumentData,
      PricingDocumentDataSlicesSlice,
      TeamDocument,
      TeamDocumentData,
      TeamDocumentDataSlicesSlice,
      AllDocumentTypes,
      AboutUsSlice,
      AboutUsSliceDefaultPrimary,
      AboutUsSliceVariation,
      AboutUsSliceDefault,
      ClothesCardsSlice,
      ClothesCardsSliceDefaultPrimarySmallImagesItem,
      ClothesCardsSliceDefaultPrimary,
      ClothesCardsSliceVariation,
      ClothesCardsSliceDefault,
      ContacUsSlice,
      ContacUsSliceDefaultPrimarySocialLinksItem,
      ContacUsSliceDefaultPrimary,
      ContacUsSliceVariation,
      ContacUsSliceDefault,
      ContactUsSupportSlice,
      ContactUsSupportSliceDefaultPrimarySupportCardsItem,
      ContactUsSupportSliceDefaultPrimary,
      ContactUsSupportSliceVariation,
      ContactUsSupportSliceDefault,
      FooterSlice,
      FooterSliceDefaultPrimaryListsItem,
      FooterSliceDefaultPrimaryCompanyInfoItem,
      FooterSliceDefaultPrimaryLegalItem,
      FooterSliceDefaultPrimaryFeaturesItem,
      FooterSliceDefaultPrimaryResourcesItem,
      FooterSliceDefaultPrimary,
      FooterSliceVariation,
      FooterSliceDefault,
      FreeComponentSlice,
      FreeComponentSliceDefaultPrimarySocialLogosItem,
      FreeComponentSliceDefaultPrimary,
      FreeComponentSliceVariation,
      FreeComponentSliceDefault,
      GrowYoursSlice,
      GrowYoursSliceDefaultPrimary,
      GrowYoursSliceVariation,
      GrowYoursSliceDefault,
      HeaderSlice,
      HeaderSliceDefaultPrimaryListItem,
      HeaderSliceDefaultPrimary,
      HeaderSliceVariation,
      HeaderSliceDefault,
      LogosSlice,
      LogosSliceDefaultPrimaryLogosItem,
      LogosSliceDefaultPrimary,
      LogosSliceVariation,
      LogosSliceDefault,
      MeetOurTeamSlice,
      MeetOurTeamSliceDefaultPrimaryUsersItem,
      MeetOurTeamSliceDefaultPrimary,
      MeetOurTeamSliceVariation,
      MeetOurTeamSliceDefault,
      PricingAfterHeaderSlice,
      PricingAfterHeaderSliceDefaultPrimary,
      PricingAfterHeaderSliceVariation,
      PricingAfterHeaderSliceDefault,
      PricingCardsSlice,
      PricingCardsSliceDefaultPrimaryCardItem,
      PricingCardsSliceDefaultPrimary,
      PricingCardsSliceVariation,
      PricingCardsSliceDefault,
      PricingfaqSlice,
      PricingfaqSliceDefaultPrimaryItemsItem,
      PricingfaqSliceDefaultPrimary,
      PricingfaqSliceVariation,
      PricingfaqSliceDefault,
    };
  }
}
