// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_us: dynamic(() => import("./AboutUs")),
  clothes_cards: dynamic(() => import("./ClothesCards")),
  contac_us: dynamic(() => import("./ContacUs")),
  contact_us_support: dynamic(() => import("./ContactUsSupport")),
  footer: dynamic(() => import("./Footer")),
  free_component: dynamic(() => import("./FreeComponent")),
  grow_yours: dynamic(() => import("./GrowYours")),
  header: dynamic(() => import("./Header")),
  logos: dynamic(() => import("./Logos")),
  meet_our_team: dynamic(() => import("./MeetOurTeam")),
  pricing_after_header: dynamic(() => import("./AfterHeader")),
  pricing_cards: dynamic(() => import("./PricingCards")),
  pricingfaq: dynamic(() => import("./Pricingfaq")),
};
